### ISSUE TITLE
Support for osx-arm64

### ISSUE THREAD

**Issue by jashapiro** [conda-forge/conda-ecosystem-user-package-isolation-feedstock#5]
### Comment:

In response to a [comment in the snakemake repository](https://github.com/snakemake/snakemake/issues/2163#issuecomment-1465577339), I decided to try out this package for some of my own environments. Unfortunately, I found that it won't quite work for my purposes (in short, I needed to set a few more ENV variables, so I decided to set them in the YAML file).

In my testing, I also found that this package is not currently available for `osx-arm64` environments. Having not worked with `conda-forge` development, I'm not sure the steps involved in adding this support, but looking at https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/ I hope it is not too complex.

**Comment by mfansler** [comment]
Thanks for pointing out that the `osx-arm64` support isn't there! There shouldn't be any reason why this can't support that and other non-x86 architectures. It's literally just a collection of shell scripts.

I can add it later today if you don't get to it first 😉

**Comment by mfansler** [comment]
Got it. See https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4247
